### ISSUE TITLE
How to understand the meaning of the intIndex in sepconv.py?

### ISSUE THREAD

**Issue by poppinjie** [sniklaus/sepconv-slomo#55]
"for (int intIndex = (blockIdx.x * blockDim.x) + threadIdx.x; intIndex < n; intIndex += blockDim.x * gridDim.x)"

What is the connection between  loop count variable intIndex and thread in GPU? If it controls the number and distribution of threads, How does it manifest?

**Comment by sniklaus** [comment]
Please see: https://stackoverflow.com/questions/16619274/cuda-griddim-and-blockdim/16619633
